### ISSUE TITLE
在vue3中使用报错t3 is not a function

### ISSUE THREAD

**Issue by laddish** [Leecason/vue-rough-notation#33]
# 简要
在vue3中使用报这个错

![image](https://user-images.githubusercontent.com/49431692/165047973-a14cead1-07f9-4b3f-96a0-c6b2cfe574f4.png)

# 在vue3中使用 复现错误
1. 使用 https://github.com/web2033/vite-vue3-tailwind-starter 模版 （或 https://github.com/antfu/vitesse-lite 模版，这两个我都试了） 创建项目
2. `npm install --save vue-rough-notation`
3. `import VueRoughNotation from 'vue-rough-notation'; app.use(VueRoughNotation);`
4. `<RoughNotation :is-show="true" type="underline">
  <span>Rough Notation is awesome</span>
</RoughNotation>`
5. 页面报上图所示错误

# 在vue2中使用 成功的案例
使用 https://github.com/lstoeferle/vite-vue2-windicss-starter 创建的 项目，引入后可以正常使用。

# 我做的尝试
在我阅读了 您在 掘金 发表的 [将 Vue 插件升级到同时支持 Vue2 和 3 的实践小结](https://juejin.cn/post/7072159954454446093) 文章后 ， 我了解到，因为 vue2 和 vue3 的 h 函数使用方法不同，我观察到您 在示例代码中 是这样去写渲染的，通过 vue-demi 的 isVue2 和 isVue3 去判断当前的vue版本，vue2 就调用render函数传入的h函数，vue3环境就调用从vue-demi中引入的h函数。
```
import { h, isVue2 } from 'vue-demi'; // 需要从 `vue-demi` 引入

render(h2) {
  ...
  
  // vue2
  if (isVue2) {
    const slot = this.$slots.default; // 默认插槽
  
    return h2('div', null, slot);
  }
  
  // vue3
  const slot = this.$slots.default(); // 默认插槽

  return h('div', null, slot);
}
```

作者：Leecason
链接：https://juejin.cn/post/7072159954454446093
来源：稀土掘金
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

但是当我看这个库的源码后，我注意到在 `src\components\RoughNotation.js`  文件中，您从 vue-demi 中引入了 h 函数 ，但是这个 h 函数并未被调用。
```
render(h2) {
    const slot =
      typeof this.$slots.default === 'function' ?
      this.$slots.default() :
      this.$slots.default;
    // console.log("h2", h2)
    if (this.tag) {
      return h2(this.tag, null, slot);
    }
    return slot && slot[0];
  },
```
我不明白为什么要这样做，所以我pull到本地，
我尝试将代码改为下面这样， 然后npm link，
```
  render(h2) {
    const slot =
      typeof this.$slots.default === 'function' ?
      this.$slots.default() :
      this.$slots.default;
    console.log("isVue2", isVue2)
    if (isVue2) {
      if (this.tag) {
        return h2(this.tag, null, slot);
      }
      return slot && slot[0];
    }
    console.log("isVue3", isVue3)
    return h(this.tag, null, slot)
  },
```

在vue2的模版（ https://github.com/web2033/vite-vue3-tailwind-starter 模版 ）中跑，令我疑惑不解的一幕出现了
![image](https://user-images.githubusercontent.com/49431692/165052467-be0989a2-f2cd-467b-8ce2-05949f909547.png)
![image](https://user-images.githubusercontent.com/49431692/165052880-92809356-b6c3-4dbe-a1b5-46e805e542ec.png)

这个项目明明是vue2的项目，为何使用vue-demi后判断为isVue2为false，isVue3为true，走的vue3的h函数，并且还报了
`[Vue warn]: Error in mounted hook: "TypeError: this._e.insertAdjacentElement is not a function"` 这样一个错。

所以是因为这个原因， 您不再使用vue-demi去判断了吗？
我想知道真实的原因，并且您知道如何解决吗？

# 背景
我最近也要使用 vue-demi 把一个vue3的库 改成一个兼容vue2 & vue3库，但是改好之后还是只能在vue3中使用，vue2报各种错， 所以想看看大佬们的代码怎么写的。

**Comment by lukaszraczylo** [comment]
Same here [ tagging along to observe ]

**Comment by Leecason** [comment]
try [v1.0.4](https://github.com/Leecason/vue-rough-notation/releases/tag/v1.0.4)

**Comment by lukaszraczylo** [comment]
Works like a charm, thank you! :)
